export const portfolioCopy = {
  en: {
    work: 'Work', talk: 'Let’s talk', available: 'Open to opportunities',
    greeting: 'Hi, I’m Subhashchandra', headline: ['Thoughtful code.', 'Meaningful', 'experiences.'],
    intro: 'A full stack developer turning complex problems into intuitive digital experiences. From the first pixel to the last API call.',
    viewWork: 'Explore my work', resume: 'View résumé', based: 'Based in Germany',
    experience: 'Years of experience', scroll: 'A little further down',
    portraitNote: 'Developer. Problem solver. Always curious.',
    experienceWith: 'A few places I’ve made an impact',
    workEyebrow: '01 / SELECTED WORK', workTitle: 'Built with purpose.',
    workIntro: 'A selection of applications, experiments, and ideas brought to life with code.',
    filters: ['All projects', 'AI', 'Full stack', 'Backend', 'Frontend', 'C# / ASP.NET'],
    allProjects: 'View all projects', lessProjects: 'Show selected projects',
    projectCount: 'projects', concept: 'Architecture concept',
    aboutEyebrow: '02 / A LITTLE ABOUT ME', aboutTitle: 'The person behind the code.',
    aboutIntro: 'I’m Subhashchandra Borad, a full stack developer who enjoys making complex things feel simple.',
    aboutBody: 'For 8+ years, I’ve built web applications for research, industry, and businesses. I connect thoughtful interfaces with dependable backends, with a focus on clean architecture and code that’s a pleasure to maintain.',
    aboutClosing: 'Currently building research information systems at the Leibniz Institute (IOER) in Dresden. Always learning, always building.',
    aboutLink: 'More about my experience', approach: 'HOW I LIKE TO WORK',
    principles: ['Understand the problem.', 'Build with intention.', 'Make it better, together.'],
    principlesBody: ['Good software starts with the right questions.', 'Clean code. Clear decisions. Room to grow.', 'Thoughtful collaboration, from idea to delivery.'],
    skillsEyebrow: '03 / MY TOOLKIT', skillsTitle: 'The right tools. Real solutions.',
    skillsIntro: 'A versatile stack, backed by hands-on experience from frontend to infrastructure.',
    categories: ['Frontend', 'Backend', 'Databases', 'APIs & architecture', 'DevOps & infrastructure', 'E-commerce & CMS', 'Security', 'Testing', 'Leadership'],
    contactEyebrow: '04 / WHAT’S NEXT?', contactTitle: ['Have something', 'in mind?'],
    contactIntro: 'A project, an opportunity, or just a good conversation. I’d love to hear from you.',
    contactNote: 'Open to full-time, freelance, and part-time opportunities.',
    namePlaceholder: 'Your name', emailPlaceholder: 'you@example.com',
    subjectPlaceholder: 'What would you like to talk about?', messagePlaceholder: 'Tell me a little about your idea…',
    optional: 'optional', sending: 'Sending…', sent: 'Thanks for reaching out! Your message has been sent.',
    error: 'Your message couldn’t be sent. Please try again or connect with me on LinkedIn.',
    formNote: 'Your message is sent securely through Getform.',
    footer: 'Made with care. Built with Next.js.', top: 'Back to top',
    menu: 'Open navigation', closeMenu: 'Close navigation', theme: 'Toggle color theme', language: 'Switch to German',
  },
  de: {
    work: 'Projekte', talk: 'Kontakt', available: 'Offen für neue Möglichkeiten',
    greeting: 'Hi, ich bin Subhashchandra', headline: ['Durchdachter Code.', 'Erlebnisse mit', 'Mehrwert.'],
    intro: 'Full Stack Entwickler mit einem Blick für intuitive digitale Erlebnisse. Vom ersten Pixel bis zum letzten API-Aufruf.',
    viewWork: 'Meine Projekte', resume: 'Zum Lebenslauf', based: 'In Deutschland zuhause',
    experience: 'Jahre Erfahrung', scroll: 'Mehr entdecken',
    portraitNote: 'Entwickler. Problemlöser. Immer neugierig.',
    experienceWith: 'Hier habe ich bereits etwas bewegt',
    workEyebrow: '01 / AUSGEWÄHLTE PROJEKTE', workTitle: 'Mit Überzeugung entwickelt.',
    workIntro: 'Eine Auswahl an Anwendungen, Experimenten und Ideen, die durch Code Wirklichkeit wurden.',
    filters: ['Alle Projekte', 'KI', 'Full Stack', 'Backend', 'Frontend', 'C# / ASP.NET'],
    allProjects: 'Alle Projekte ansehen', lessProjects: 'Auswahl anzeigen',
    projectCount: 'Projekte', concept: 'Architekturkonzept',
    aboutEyebrow: '02 / ÜBER MICH', aboutTitle: 'Der Mensch hinter dem Code.',
    aboutIntro: 'Ich bin Subhashchandra Borad, Full Stack Entwickler. Ich mache komplexe Dinge gerne einfach.',
    aboutBody: 'Seit über 8 Jahren entwickle ich Webanwendungen für Forschung, Industrie und Unternehmen. Ich verbinde durchdachte Oberflächen mit zuverlässigen Backends und lege Wert auf saubere Architektur und gut wartbaren Code.',
    aboutClosing: 'Aktuell entwickle ich Forschungsinformationssysteme am Leibniz-Institut (IÖR) in Dresden. Immer am Lernen, immer am Entwickeln.',
    aboutLink: 'Mehr über meine Erfahrung', approach: 'SO ARBEITE ICH',
    principles: ['Das Problem verstehen.', 'Bewusst entwickeln.', 'Gemeinsam besser werden.'],
    principlesBody: ['Gute Software beginnt mit den richtigen Fragen.', 'Sauberer Code. Klare Entscheidungen. Raum zum Wachsen.', 'Gute Zusammenarbeit, von der Idee bis zur Umsetzung.'],
    skillsEyebrow: '03 / MEIN WERKZEUGKASTEN', skillsTitle: 'Gute Werkzeuge. Echte Lösungen.',
    skillsIntro: 'Ein vielseitiger Stack mit praktischer Erfahrung vom Frontend bis zur Infrastruktur.',
    categories: ['Frontend', 'Backend', 'Datenbanken', 'APIs & Architektur', 'DevOps & Infrastruktur', 'E-Commerce & CMS', 'Sicherheit', 'Testing', 'Teamarbeit'],
    contactEyebrow: '04 / WAS KOMMT ALS NÄCHSTES?', contactTitle: ['Eine Idee', 'im Kopf?'],
    contactIntro: 'Ein Projekt, eine neue Möglichkeit oder ein gutes Gespräch. Ich freue mich auf deine Nachricht.',
    contactNote: 'Offen für Festanstellung, Freelance- und Teilzeitprojekte.',
    namePlaceholder: 'Dein Name', emailPlaceholder: 'du@beispiel.de',
    subjectPlaceholder: 'Worüber möchtest du sprechen?', messagePlaceholder: 'Erzähl mir etwas über deine Idee…',
    optional: 'optional', sending: 'Wird gesendet…', sent: 'Vielen Dank! Deine Nachricht wurde gesendet.',
    error: 'Die Nachricht konnte nicht gesendet werden. Bitte versuche es erneut oder kontaktiere mich auf LinkedIn.',
    formNote: 'Deine Nachricht wird sicher über Getform gesendet.',
    footer: 'Mit Sorgfalt gestaltet. Mit Next.js entwickelt.', top: 'Nach oben',
    menu: 'Navigation öffnen', closeMenu: 'Navigation schließen', theme: 'Farbschema wechseln', language: 'Switch to English',
  },
};
